[package]
name = "witchcraft-log"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
conjure-error = "0.5"
erased-serde = "0.3"
lazycell = "1.0"
log = "0.4"
serde = "1.0"

[dev-dependencies]
serde_test = "1.0"
serde-value = "0.6"
